### ISSUE TITLE
milestone 2 feedback

### ISSUE THREAD

**Issue by roozbehes** [data301-2020-winter1/course-project-solo_6023-2#1]
Good job

- [ ] it's better to provide explanation for each graph after it and explain what you see and how that answers your research questions.

- [ ] explore different types of graphs. you only have bar charts. it's better to have different ways to show the results of your research

**Comment by markonuke** [comment]
Edited the milestone 2 python lab notebook

**Comment by markonuke** [comment]
I tried to include different versions but since most of the entries are non-numerical, it is hence I plotted as bar charts. More/different types of visualizations are created using Tableau. The tableau workbook is uploaded in the repository.
